# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/bin/', 'README.md', 'INSTALL.md', 'LICENSE.txt', 'CNAME']
include: ['_pages']

# Site Settings
title: "FOSS4G 2023"
# email: "test@example.com"
description: "FOSS4G is the acronym for Free and Open Source Software for Geospatial."
baseurl: ""
url: "https://2023.foss4g.org"
permalink: "/blog/:title"

# Organizer Info
# organizerName: "FLOSSK"
# organizerAlternateName: "Free Libre Open Source Software Kosova"
# organizerDescription: ""
# organizerEmail: "info@flossk.org"
# organizerLogo: "/img/organizers/flossk-logo.svg"
# organizerLink: "https://flossk.org/"

# Head
# metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
# twitterAccount: "@DevFest"
# socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
# socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
# socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"

# Navigation
navigationLinks:
 - {permalink: "/about/", text: "FOSS4G 2023"}
 - {permalink: "/register/", text: "Register"}
 - {permalink: "/call-for-papers/", text: "Call for papers"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/sponsors/", text: "Sponsors"}
 - {permalink: "/attending/", text: "Attending"}
 - {permalink: "/blog/", text: "News"}
#  - {permalink: "/speakers/", text: "Speakers"}
#  - {permalink: "/team/", text: "Team"}
#  - {permalink: "/logistics/", text: "Logistics"}
#  - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroTitle: "FOSS4G <typeout> 2023"
eventDate: "26 June - 2 July 2023"
# typeoutTextValues: '"", "Season", "Ukraine", "Germany", "USA"'
# typeoutFallback: "Season"
heroButtons:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# Statistic Block
# statisticBlockImage: "statistic.jpg"
# statisticBlock:
#  - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
#  - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
#  - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
#  - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Rockstar Speakers Block
rockstarSpeakersCount: 4

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Innovation and Training Park (ITP)"
eventLocationLink: "https://itp-prizren.com/"
eventStreetAddress: "Ukë Bytyçi"
eventAddressLocality: "Prizren"
eventAddressLocalityRegion: ""
eventPostalCode: "20000"
eventAddressCountry: "Kosovo"
eventStartTime: "2023-06-26T10:00"
eventDoorTime: "09:00"
eventEndTime: "2023-07-01T20:00"
eventPlaceCoordinates: "42.22097, 20.75224"
mapCenterCoordinates: "42.22097, 20.75224"
# mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBigImage: "itp-aerial.jpg"
venueSmallImage1: "ITP-Prizren1.jpg"
venueSmallImage2: "itp-building.jpg"
venueSmallImage3: "ITP-Prizren6.jpg"
venueTitle: "Innovation and Training Park"
venueText: The Innovation and Training Park is a former military camp, in the outskirts of the beautiful city of Prizren. The ITP is far more than a classic business park. The ITP ensures close linkages among tenants as well as between park management and tenants, offering an environment that fosters synergies between the private sector, vocational education and training institutions, and innovation activities.

# Tweets Feed Block
# tweetsFeedImage: "twitter-feed.jpg"
# tweetsFeedTitle: "What's Up?"
# twitterHashTag: "devfest"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://twitter.com/foss4g", icon: "twitter"}
 - {link: "https://www.youtube.com/foss4g", icon: "youtube"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.osgeo.org/", text: "OSGEO"}
   - {link: "https://flossk.org/", text: "FLOSSK"}
   - {link: "https://foss4g.org/", text: "FOSS4G past events"}
 -
  title: "Contact us"
  links:
    - {link: "mailto:info@foss4g.org", text: "General questions: info@foss4g.org"}
    - {link: "mailto:register@foss4g.org", text: "Registration: register@foss4g.org"}
    - {link: "mailto:sponsors@foss4g.org", text: "Sponsor questions: sponsors@foss4g.org"}
    - {link: "mailto:callforpapers@foss4g.org", text: "Call for papers: callforpapers@foss4g.org"}
    - {link: "mailto:academic.foss4g2023@gmail.com", text: "Academic papers: academic.foss4g2023@gmail.com"}
    - {link: "https://twitter.com/foss4g", text: "Twitter"}
    - {link: "https://www.youtube.com/c/FOSS4G", text: "YouTube"}
 -
  title: "Useful links"
  links:
   - {permalink: "/code-of-conduct/", text: "Code of Conduct"}
   - {permalink: "/privacy/", text: "Privacy Policy"}
   - {permalink: "/about/faq/", text: "Frequently Asked Questions (FAQ)"}
   - {permalink: "/about/team/", text: "Committee"}
   - {permalink: "/about/branding/", text: "Branding"}

# Blog
# blogCommentsEnabled: true
# discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Logistics Find Way Block
# findWayTitle: "Find your way here"
# findWayDistance: "Distance"
# findWayDriving: "DRIVING"
# findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
# findWayTransit: "TRANSIT"
# findWayFindFlight: "Find Flight"
# logisticsMapCenterCoordinates: "49.056728, 3.117289"
# logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
# logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsCards:
  - {title: "Visa info", information: "Kosovo requires visas for citizens of certain countries. You can find more information on which participants will need a visa to come to Kosovo here: <https://en.wikipedia.org/wiki/Visa_policy_of_Kosovo>.  \nFLOSSK will issue a visa letter should you need one and will facilitate the visa process so you don’t need to visit a Kosovo Consulate."}
  - {title: "Travel Safety", information: "Kosovo is a safe country to travel and foreigners are much appreciated and helped. Crimes against tourists common in popular tourist destinations are not common in Kosovo.  \nThe risk of terrorist attacks in the Kosovo over the past years can be classified as almost insignificant. Violent crime exists but is mostly related to organized crime, and most dangers are of petty nature and between persons familiar to each other.  \nKosovo’s medical system is lacking. However, even foreigners can get care, including emergency care, for a handful of euros. Private clinics are also numerous but at a higher cost."}
  - {title: "COVID-19 safety plans", information: "COVID-19 situation in Kosovo is stable as of now. We will update this section if the situation changes in the meanwhile starting with ticket sale launch, especially considering the current global Covid-19 situation. It is likely vaccine currency will be required."}
  - {title: "Political situation", information: "Some of you might remember that Kosovo went through a war in 1999. That was 22 years ago, although some political tensions still linger with Serbia. That said, what you see on the news is largely for internal political consumption. Kosovo is protected by a NATO peacekeeping force. Ethnic tensions might be present, limited in the northern corner of the country."}
  - {title: "LGBTIQ+ Safety", information: "Summer festivals and international events in Kosovo are usually very safe and inclusive towards many groups, such as the LGBTIQ+ community. Women can travel alone and there aren’t any specific laws against the LGBTIQ+ community. Nevertheless, there is a level of sexism and homophobia among some, accompanied by verbal harassment."}
directionDetailsWideCards:
 - title: "Getting to Prizren"
   information: "All international flights to Kosovo arrive at the Prishtina International Airport. From Prishtina International Airport there is a Public transport bus line from Prishtina International Airport to the Bus Station in Prishtina. Bus lines from Prishtina Bus Station to Prizren travel every 20 minutes (5 EUR).  \nKosovo has border points with Albania, North Macedonia, Montenegro, and Serbia which may be used to enter the country.  \nOther than Prishtina International Airport, for cost considerations, participants can also use 3 other airports in the region which offer better priced airline tickets from some destinacions and especially if you are doing some tourism before or after arriving in Kosovo:"
   subCards:
    - title: "From Tirana International Airport"
      information: "2:10 hrs by bus (163 km) away. Tirana - Prishtina bus stops by Tirana International Airport with a stopover in the periphery of Prizren, from which you may call a taxi."
      links: [{link: "https://www.tirana-airport.com/", text: "Tirana International Airport"}]
    - title: "From Skopje International Airport"
      information: "Might also have better deals through Wizz Air and alternative destinations from those in Prishtina. It will take 3-4 hrs all if best connected."
      links: [{link: "http://skp.airports.com.mk/", text: "Skopje International Airport"}]
    - title: "From Kukës International Airport"
      information: "Newly opened airport, in northern Albania, across the border from Prizren, with a handful of lines, currently only serving Switzerland, mostly through charter lines. Get to the town of Kukës, from there vans (furgon) are regular to Prizren."
      links: [{link: "https://www.kuiport.al/", text: "Kukës International Airport"}]

# Hackathon
# hackathonTitle: "Hackathon"
# enableHackathon: true

# Hackathon About Block
# aboutHackathonTitle: "Meet our themes"
# hackathonRows:
#  - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
#  - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
#  - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
# judgesImage: "judges.jpg"
# judgesTitle: "Judges"

# Hackathon Prizes Block
# prizesTitle: "Prizes"
# prizes:
#  - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
#  - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
#  - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
# hackathonLocationBlockTitle: "Location"
# hackathonLocationName: "Communa"
# hackathonLocationLink: "http://communa.net.ua/"
# hackathonStreetAddress: "1 Halytska St"
# hackathonAddressLocality: "Lviv"
# hackathonAddressLocalityRegion: "Lvivska"
# hackathonPostalCode: "79000"
# hackathonAddressCountry: "Ukraine"
# hackathonTimeTitle: "Hack through"
# hackathonStartTime: "2014-10-24T10:00"
# hackathonDoorTime: "09:00"
# hackathonEndTime: "2014-10-25T00:00"
# viewOnMap: "View on Google Maps"
# hackathonPlaceCoordinates: "49.840999, 24.031144"
# hackathonMapCenterCoordinates: "49.840696, 24.028754"
# hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
