baseURL = "https://2021.foss4g.org/"
title = "FOSS4G 2021 Buenos Aires"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
#googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = ["foss4g2021", "infinity-hugo"]
uglyurls = true

#Languages
[languages.en]
weight = 0
languageName = "English"

[languages.es]
weight = 10
languageName = "Spanish"
  [languages.es.params]
    author = "Comité de organización de Buenos Aires"
    description = "Contra viento y Marea, FOSS4G"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Buenos Aires Local Organization Committee"
  description = "Come rain or shine, FOSS4G"
  homepageImage = "/images/people.png"
  share = true
  showLanguageSwitcher = true

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ["styles.css"]
  customJS = []

  [params.social]
    rss = true
    email = "foss4g2021ba@gmail.com"
    facebook = "https://www.facebook.com/foss4g2021ba/"
    twitter = "https://twitter.com/foss4g"
    linkedin = "https://www.linkedin.com/foss4g-2021-ba"
#    stack-overflow = "https://stackoverflow.com"
    instagram = "https://www.instagram.com/foss4g2021/"
#    github = "https://github.com"
#    weibo = "https://www.weibo.com"
#    medium = "https://medium.com"
#    pinterest = "https://pinterest.com"
#    reddit = "https://reddit.com"
#    gitlab = "https://gitlab.com"
#    mastodon = "https://mastodon.social"
#    keybase = "https://keybase.io/"

  [params.hero]
  enable            = true
  # bg                = "images/header-bg.jpg"
  # title             = "FOSS4G starts in:"
  # subtitle          = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna"
  # btnText           = "Get Started"

  # counter
  disableCountdown  = false
  countdownYear = "2021"
  countdownMonth = "09"
  countdownDay  = "27"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
