baseURL = "https://2021.foss4g.org/"
title = "FOSS4G 2021 Buenos Aires"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
#googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "foss4g2021"
uglyurls = true

#Languages
[languages.en]
weight = 0
languageName = "English"

[languages.es]
weight = 10
languageName = "Spanish"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Buenos Aires Organization Committee"
  description = "The International GeoSpatial Conference"
  homepageImage = "/images/people.png"
  share = true
  showLanguageSwitcher = true

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ["styles.css"]
  customJS = []

  [params.social]
    rss = true
    email = "foss4g2021ba@gmail.com"
    facebook = "https://www.facebook.com/foss4g2021ba/"
    twitter = "https://twitter.com/foss4g"
    linkedin = "https://www.linkedin.com/foss4g-2021-ba"
#    stack-overflow = "https://stackoverflow.com"
    instagram = "https://www.instagram.com/foss4g2021/"
#    github = "https://github.com"
#    weibo = "https://www.weibo.com"
#    medium = "https://medium.com"
#    pinterest = "https://pinterest.com"
#    reddit = "https://reddit.com"
#    gitlab = "https://gitlab.com"
#    mastodon = "https://mastodon.social"
#    keybase = "https://keybase.io/"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
