# Change to 2020.foss4g.org in the future:
baseURL = "https://foss4g-2021.gitlab.io/"
title = "FOSS4G 2021 Buenos Aires"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
#googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

#Languages
[languages.en]
weight = 0
languageName = "English"

[languages.es]
weight = 10
languageName = "Spanish"


#Menu in English
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "register"
    name = "Register"
    url = "/register/"
    weight = 0
  [[menu.main]]
    identifier = "call-for-papers"
    name = "Call For Papers"
    url = "/call-for-papers/"
    weight = 0
  [[menu.main]]
    identifier = "call-for-papers-talks"
    parent = "call-for-papers"
    name = "Call for papers-talks"
    url = "/call-for-papers/talks"
    weight = 0
  [[menu.main]]
    identifier = "call-for-papers-academic"
    parent = "call-for-papers"
    name = "Call for papers-academic"
    url = "/call-for-papers/academic"
    weight = 0
  [[menu.main]]
    identifier = "call-for-papers-workshop"
    parent = "call-for-papers"
    name = "Call for papers-workshop"
    url = "/call-for-papers/workshop"
    weight = 0
  [[menu.main]]
    identifier = "schedule"
    name = "Schedule"
    url = "/schedule/"
    weight = 0
  [[menu.main]]
    identifier = "sponsorship"
    name = "Sponsorship"
    url = "/sponsorship/"
    weight = 0
  [[menu.main]]
    identifier = "sponsorship-our-sponsors"
    parent = "sponsorship"
    name = "sponsorship-our-sponsors"
    url = "/sponsorship/our-sponsors"
    weight = 0
  [[menu.main]]
    identifier = "sponsorship-sponsorship-opportunities"
    parent = "sponsorship"
    name = "sponsorship-sponsorship-opportunities"
    url = "/sponsorship/sponsorship-opportunities"
    weight = 0
  [[menu.main]]
    identifier = "venue"
    name = "Location and Venue"
    url = "/location-and-venue/"
    weight = 0
  [[menu.main]]
    parent = "venue"
    name = "Traveling to Buenos Aires"
    identifier = "venue-traveling-to-buenos-aires"
    url = "/location-and-venue/traveling-to-buenos-aires"
    weight = 0
  [[menu.main]]
    parent = "venue"
    name = "Traveling inside Buenos Aires"
    identifier = "venue-traveling-inside-buenos-aires"
    url = "/location-and-venue/traveling-inside-buenos-aires"
    weight = 0
  [[menu.main]]
    parent = "venue"
    name = "Venue"
    identifier = "venue-venue"
    url = "/location-and-venue/venue"
    weight = 0
  [[menu.main]]
    parent = "venue"
    name = "Accomodations"
    identifier = "venue-accomodations"
    url = "/location-and-venue/accomodations"
    weight = 0
  [[menu.main]]
    parent = "venue"
    name = "Tourism"
    identifier = "venue-tourism"
    url = "/location-and-venue/tourism"
    weight = 0


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Buenos Aires Organization Committee"
  description = "The International GeoSpatial Conference. Coming Soon!"
  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = true

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "foss4g2021ba@gmail.com"
    facebook = "https://www.facebook.com/foss4g2021ba/"
    twitter = "https://twitter.com/foss4g"
    linkedin = "https://www.linkedin.com/foss4g-2021-ba"
#    stack-overflow = "https://stackoverflow.com"
    instagram = "https://www.instagram.com/foss4g2021/"
#    github = "https://github.com"
#    weibo = "https://www.weibo.com"
#    medium = "https://medium.com"
#    pinterest = "https://pinterest.com"
#    reddit = "https://reddit.com"
#    gitlab = "https://gitlab.com"
#    mastodon = "https://mastodon.social"
#    keybase = "https://keybase.io/"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
