baseURL = "https://2019.foss4g.org"
title = "FOSS4G 2021 Buenos Aires"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
#googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "register"
    name = "Register"
    url = "/register/"
    weight = 0
  [[menu.main]]
    identifier = "call-for-papers"
    name = "Call for papers"
    url = "/call-for-papers/"
    weight = 0
    [[menu.nest]]
      identifier = "call-for-papers"
      name = "Call for papers"
      url = "/call-for-papers/"
      weight = 0
  [[menu.main]]
    identifier = "schedule"
    name = "Schedule"
    url = "/schedule/"
    weight = 0
  [[menu.main]]
    identifier = "sponsorship"
    name = "Sponsorship"
    url = "/sponsorship/"
    weight = 0
  [[menu.main]]
    identifier = "venue"
    name = "Location and Venue"
    url = "/location-and-venue/"
    weight = 0


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Hugo Authors"
  description = "Lorem ipsum dolor sit amet."
  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "example@example.com"
#    facebook = "https://facebook.com"
#    twitter = "https://twitter.com"
#    linkedin = "https://linkedin.com"
#    stack-overflow = "https://stackoverflow.com"
#    instagram = "https://stackoverflow.com"
#    github = "https://github.com"
#    weibo = "https://www.weibo.com"
#    medium = "https://medium.com"
#    pinterest = "https://pinterest.com"
#    reddit = "https://reddit.com"
#    gitlab = "https://gitlab.com"
#    mastodon = "https://mastodon.social"
#    keybase = "https://keybase.io/"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
