title = "FOSS4G 2021 Buenos Aires"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
#googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = ["foss4g2021"]
uglyurls = true
enableRobotsTXT = true

#Languages
[languages.en]
weight = 0
languageName = "English"

  [[languages.en.menu.main]]
  name   = "About"
  weight = 10
  [[languages.en.menu.main]]
  name   = "Call for Papers"
  weight = 20
  [[languages.en.menu.main]]
  name   = "Register"
  weight = 30
  [[languages.en.menu.main]]
  name   = "Schedule"
  weight = 40
  [[languages.en.menu.main]]
  name   = "Sponsor"
  weight = 50

[languages.es]
weight = 10
languageName = "Spanish"
  [languages.es.params]
    author = "OSGeo y GeoLibres"
    description = "Contra viento y marea, FOSS4G"
    dates = "27 de Septiembre a 2 de Octubre de​ 2021"

  [[languages.es.menu.main]]
  name   = "Acerca de"
  weight = 10
  [[languages.es.menu.main]]
  name   = "Presentaciones"
  weight = 20
  [[languages.es.menu.main]]
  name   = "Registrate"
  weight = 30
  [[languages.es.menu.main]]
  name   = "Programa"
  weight = 40
  [[languages.es.menu.main]]
  name   = "Patrocinios"
  weight = 50

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "OSGeo and GeoLibres"
  description = "Come hell or high water, FOSS4G"
  dates = "September 27​th​ to October 2​nd​ 2021"
  homepageImage = "/images/people.webp"
  share = true
  showLanguageSwitcher = true

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ['fontello.css']
  customJS = []

  [params.social]
    rss = true
    email = "foss4g2021ba@gmail.com"
    facebook = "https://www.facebook.com/foss4g2021ba/"
    twitter = "https://twitter.com/foss4g"
    linkedin = "https://www.linkedin.com/company/foss4g-2021-ba/"
#    stack-overflow = "https://stackoverflow.com"
    instagram = "https://www.instagram.com/foss4g2021/"
#    github = "https://github.com"
#    weibo = "https://www.weibo.com"
#    medium = "https://medium.com"
#    pinterest = "https://pinterest.com"
#    reddit = "https://reddit.com"
#    gitlab = "https://gitlab.com"
#    mastodon = "https://mastodon.social"
#    keybase = "https://keybase.io/"
    subscribe = "http://eepurl.com/gxPUJH"

  [params.hero]
  enable            = true
  # bg                = "images/header-bg.jpg"
  # title             = "FOSS4G starts in:"
  # subtitle          = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna"
  # btnText           = "Get Started"

  # counter
  disableCountdown  = false
  countdownYear = "2021"
  countdownMonth = "09"
  countdownDay  = "27"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
