# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "foss4g2021"
license = "GPL"
licenselink = "https://gitlab.com/foss4g-2021/foss4g-2021.gitlab.io/-/blob/master/LICENSE"
description = "Theme for FOSS4G2021 based on Chunky Poster"
homepage = "https://2021.foss4g.org"
tags = ["minimal", "minimalist", "blog", "responsive", "syntax highlighting", "multilingual", "minimalist", "light"]
features = ["minimal", "minimalist", "blog", "responsive", "syntax highlighting", "multilingual", "minimalist", "light"]
min_version = "0.41"

[author]
  name = "FOSS4G 2021 BALOC"
  homepage = "https://2021.foss4g.org"

# Based on existing theme
[original]
  name = "Chunky Poster"
  homepage = "https://github.com/puresyntax71/hugo-theme-chunky-poster"
  repo = "https://github.com/puresyntax71/hugo-theme-chunky-poster"
